### ISSUE TITLE
[8h] Create diagrams

### ISSUE THREAD

**Issue by mateuszwu** [mateuszwu/GPP-1#3]

**Comment by PDendys** [comment]
Components diagram created.
link: https://drive.google.com/file/d/0B9awJzU6WOtbYTBwU3MtS1NFRms/view?usp=sharing

**Comment by bartoszboruta** [comment]
Use case diargam created.
Link: [https://drive.google.com/open?id=0BxnvvWlzb3O9dDhaMENZQTBDMkk]
