### ISSUE TITLE
[8h] Create functionality list

### ISSUE THREAD

**Issue by mateuszwu** [mateuszwu/GPP-1#4]

**Comment by PDendys** [comment]
Unfunctionality list done.
https://docs.google.com/document/d/1MZXzA0Kzi-WWVvQdu6XcpwIaR13aiPMxEwC9z4AEqnA/edit

**Comment by mateuszwu** [comment]
Funcionality list.
https://docs.google.com/document/d/15zL7bE49c_vxZ-bNadbaY7Y1O2kUfHVEEevJ0IlNHq4/edit
